name: mookata
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  qrscan: ^0.3.3
  url_launcher: ^6.2.5
  flutter_automation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
